# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Dobruckhin
                                 A QGIS plugin
 This plugin finds buildings (short version)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-03
        copyright            : (C) 2025 by Dobruckhin Grigorii
        email                : .
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Dobruckhin class from file Dobruckhin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Dobruckhin import Dobruckhin
    return Dobruckhin(iface)
